# Generated by Django 4.1 on 2022-08-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='phone',
        ),
        migrations.AddField(
            model_name='links',
            name='email',
            field=models.EmailField(default='1:57', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='links',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
